apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
spec:
  selector:
    app: ingestion
  ports:
    - protocol: TCP
      port: 8080          # Port exposed by the service
      targetPort: 8080    # Port on the container
  type: NodePort          # Exposes the service on a port on the host