spring:
  cloud:
    kubernetes:
      enabled: true
      secrets:
        enabled: true
        name: my-kafka-user-passwords
        namespace: default

my:
  kafka:
    username: user1
    password: ${KAFKA_PASSWORD}
  minio:
    bucketname: audit-bucket
    username: admin
    password: ${MINIO_PASSWORD}
    url: http://minio.default.svc.cluster.local:9000
