apiVersion: apps/v1
kind: Deployment
metadata:
  name: retrieval-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retrieval
  template:
    metadata:
      labels:
        app: retrieval
    spec:
      containers:
        - name: retrieval
          image: retrieval:18.07.2024
          env:
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: root-password
            - name: AES_KEY
              valueFrom:
                secretKeyRef:
                  name: aes-key
                  key: key
