apiVersion: v1
kind: Service
metadata:
  name: retrieval-service
spec:
  type: NodePort  # Specify the type as NodePort to expose the service
  selector:
    app: retrieval
  ports:
    - protocol: TCP
      port: 80 # Port on the NodePort service (external access)
      targetPort: 8080  # Port on the pods (internal access)
